version: '3'

services:

  api:
    container_name: briefing-api
    build: .
    env_file:
      - secrets.env
    ports:
      - 8000:8000
    volumes:
      - files:/var/files
    restart: always
    depends_on:
      - db

  db:
    container_name: briefing-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - secrets.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  files:
  mysql:
